blueprint:
  name: Log template
  description: Log event on slack
  domain: automation
  input:
    trigger_sensor:
      selector:
        entity:
          domain: binary_sensor
    message:
      name: Message
      default: '{{ entity_name }} {{entity_state}} ({{now().strftime("%H:%M:%S") }})'
    picto:
      name: Picto
      default: "🏡"
    title:
      name: Title
      default: "HA - Ouverture"

trigger:
  - platform: state
    entity_id: !input trigger_sensor
    to: "on"
variables:
  entity_name: "{{ states[trigger.entity_id].name }}"
  entity_state: "{{ states[trigger.entity_id].state }}"
  picto: !input "picto"
  message: !input "message"
action:
  - service: notify.slack_ha
    data_template:
      message: "{{ picto }} {{ message }}"
      target: "#général"
  - service: notify.mobile_app_iphone_12_de_pouzor
    data_template:
      message: "{{ picto }} {{ message }}"
      title: !input "title"
